##SMS Alert
#SMS.Gateway.SQL.DBConnection=jdbc:sqlserver://10.1.106.104;DatabaseName=NotificationAlert
#SMS.Gateway.SQL.User=sa
#SMS.Gateway.SQL.Password=Thunn@2011
##Mail Alert
#NotificationAlert.From=noreply@cbbank.com.mm
#NotificationAlert.Host=172.16.5.23
#NotificationAlert.Port=255


# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

# Define the root logger with appender file  
log = /home/T24/Jboss_PROD/standalone/log  
log4j.rootLogger = DEBUG, FILE  
  
# Define the file appender  
log4j.appender.FILE=org.apache.log4j.FileAppender  
log4j.appender.FILE.File=${log}/log.out  
  
# Define the layout for file appender  
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout  
log4j.appender.FILE.layout.conversionPattern=%m%n  