# Database Connection Settings
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.user=vwuser
db.password=vwuser1234!

# Connection Strings (Double check IPs for Prod)
db.url.notification=jdbc:sqlserver://10.1.32.13\\MSSQLSERVER2017;DatabaseName=NotificationAlert
db.url.report=jdbc:sqlserver://10.1.32.13\\MSSQLSERVER2017;DatabaseName=TMT24ReportDB
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

